/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agenciafiscalpresentacion;

import com.mycompany.agenciafiscaldtos.ClienteDTO;
import com.mycompany.agenciafiscaldtos.LicenciaDTO;
import com.mycompany.agenciafiscaldtos.LicenciaNuevaDTO;
import com.mycompany.agenciafiscalnegocio.ITramitarLicenciaBO;
import com.mycompany.agenciafiscalnegocio.TramitarLicenciaBO;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Berry
 */
public class FormLicencias extends javax.swing.JFrame {

    private DefaultListModel<String> modeloLista;
    private ITramitarLicenciaBO tramitarLicenciaBO;
    private ClienteDTO clienteDTO;

    /**
     * Creates new form FormRenovarLicencias
     */
    public FormLicencias() {
        initComponents();
        modeloLista = new DefaultListModel<>();
        this.tramitarLicenciaBO = new TramitarLicenciaBO();
        mostrarBotones(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panFondoBlanco = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        panEntrar = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        txtRfc = new javax.swing.JLabel();
        txtVigencia = new javax.swing.JLabel();
        txfRfc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panCosto = new javax.swing.JPanel();
        txtCosto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JLabel();
        cbxVigencia = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListDatosCliente = new javax.swing.JList<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));

        panHeader.setBackground(new java.awt.Color(217, 217, 217));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/AgenciaFiscal.png"))); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        txtTitulo.setText("Licencias");

        btnCerrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCerrar.setText("Cancelar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(22, 22, 22))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo)
                    .addGroup(panHeaderLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panHeaderLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnCerrar))
                            .addComponent(txtTitulo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panEntrar.setBackground(new java.awt.Color(236, 236, 236));

        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtRfc.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtRfc.setText("RFC:");

        txtVigencia.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtVigencia.setText("Vigencia:");

        txfRfc.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        panCosto.setBackground(new java.awt.Color(217, 217, 217));

        txtCosto.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtCosto.setText("Costo:");

        txtMonto.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        txtMonto.setText("$0.0");

        javax.swing.GroupLayout panCostoLayout = new javax.swing.GroupLayout(panCosto);
        panCosto.setLayout(panCostoLayout);
        panCostoLayout.setHorizontalGroup(
            panCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCostoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtCosto)
                .addGap(243, 243, 243)
                .addComponent(txtMonto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCostoLayout.setVerticalGroup(
            panCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCostoLayout.createSequentialGroup()
                .addGroup(panCostoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCostoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtCosto))
                    .addGroup(panCostoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMonto)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cbxVigencia.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cbxVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Año", "2 Años", "3 Años" }));
        cbxVigencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxVigenciaItemStateChanged(evt);
            }
        });
        cbxVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVigenciaActionPerformed(evt);
            }
        });

        ListDatosCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ListDatosCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nombre:", "RFC", "Telefono", "Fecha de Nacimiento:", "Discapacitado:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListDatosCliente);

        javax.swing.GroupLayout panEntrarLayout = new javax.swing.GroupLayout(panEntrar);
        panEntrar.setLayout(panEntrarLayout);
        panEntrarLayout.setHorizontalGroup(
            panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panEntrarLayout.createSequentialGroup()
                .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEntrarLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btnAceptar))
                    .addGroup(panEntrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVigencia)
                            .addComponent(txtRfc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panEntrarLayout.createSequentialGroup()
                                .addComponent(txfRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(cbxVigencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEntrarLayout.setVerticalGroup(
            panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEntrarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEntrarLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRfc)
                            .addComponent(txfRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVigencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(panEntrarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(btnAceptar)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout panFondoBlancoLayout = new javax.swing.GroupLayout(panFondoBlanco);
        panFondoBlanco.setLayout(panFondoBlancoLayout);
        panFondoBlancoLayout.setHorizontalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panFondoBlancoLayout.setVerticalGroup(
            panFondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoBlancoLayout.createSequentialGroup()
                .addComponent(panHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        FormTramites ftl = new FormTramites();
        ftl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txfRfc.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "El RFC tiene que estar lleno");
            return;
        }
        ClienteDTO clienteRFC = new ClienteDTO(txfRfc.getText());
        tramitarLicenciaBO.setCliente(clienteRFC);
        clienteDTO = tramitarLicenciaBO.consultarCliente();
        if (clienteDTO == null) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado cliente con RFC " + txfRfc.getText());
            return;
        }
        if (calcularEdad(clienteDTO.getFecha_nacimiento()) < 18) {
            JOptionPane.showMessageDialog(this, "El cliente tiene que ser mayor de edad");
            return;
        }
        llenarListDatosClientes(clienteDTO);
        actualizarCosto((String) cbxVigencia.getSelectedItem());
        mostrarBotones(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxVigenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxVigenciaItemStateChanged
        if (clienteDTO == null) {
            return;
        }
        actualizarCosto((String) cbxVigencia.getSelectedItem());
    }//GEN-LAST:event_cbxVigenciaItemStateChanged
    private int calcularEdad(Calendar nacimiento) {

        Calendar today = Calendar.getInstance();
        int age = today.get(Calendar.YEAR) - nacimiento.get(Calendar.YEAR);
        if (today.get(Calendar.DAY_OF_YEAR) < nacimiento.get(Calendar.DAY_OF_YEAR)) {
            age--;
        }
        System.out.println(age);
        return age;

    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        LicenciaDTO licenciaExistente = tramitarLicenciaBO.validacionLicenciaExistencia();
        if (licenciaExistente != null) {
            int response = JOptionPane.showConfirmDialog(this, "Existe una licencia vigente hasta " + formatoFecha(licenciaExistente.getFecha_vencimiento()) + "¿Desea registrar una nueva?");
            if (response != JOptionPane.YES_OPTION) {
                return;
            }
        }
        LicenciaDTO licenciaDTO = tramitarLicencia();

        if (licenciaDTO != null) {
            JOptionPane.showMessageDialog(this, "Licencia creada ");
            mostrarBotones(false);
            limpiarDatos();

        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido crear ");
        }
        limpiarDatos();


    }//GEN-LAST:event_btnAceptarActionPerformed
    public void mostrarBotones(boolean flag) {
        txtVigencia.setVisible(flag);
        cbxVigencia.setVisible(flag);
        btnAceptar.setVisible(flag);
    }

    private LicenciaDTO tramitarLicencia() {
        String montoTexto = txtMonto.getText().substring(1);
        float monto = Float.parseFloat(montoTexto);
        LicenciaNuevaDTO licenciaNueva = new LicenciaNuevaDTO((String) cbxVigencia.getSelectedItem(), monto);
        tramitarLicenciaBO.setLicencia(licenciaNueva);
        char anios = String.valueOf(cbxVigencia.getSelectedItem()).charAt(0);
        LicenciaDTO licencia = tramitarLicenciaBO.solicitarLicencia(Integer.parseInt(String.valueOf(anios)));
        return licencia;
    }

    private void cbxVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVigenciaActionPerformed
    public void limpiarDatos() {
        txtMonto.setText("$0.0");
        txfRfc.setText("");
        cbxVigencia.setSelectedIndex(0);
        modeloLista.clear();
        tramitarLicenciaBO = new TramitarLicenciaBO();
        clienteDTO = null;
    }

    public void actualizarCosto(String año) {
        if (clienteDTO == null) {
            return;
        }
        txtMonto.setText("$" + tramitarLicenciaBO.calcularCosto(año));
    }

    public void limpiarListaDatosCliente() {
        modeloLista.clear();
    }

    public void llenarListDatosClientes(ClienteDTO clienteDTO) {
        limpiarListaDatosCliente();
        modeloLista.addElement("Nombre: " + clienteDTO.getNombre() + " " + clienteDTO.getApellido_paterno() + " " + clienteDTO.getApellido_materno());
        modeloLista.addElement("RFC: " + clienteDTO.getRfc());
        modeloLista.addElement("Telefono: " + clienteDTO.getTelefono());
        modeloLista.addElement("Fecha de Nacimiento: " + formatoFecha(clienteDTO.getFecha_nacimiento()));
        if (clienteDTO.getDiscapacitado()) {
            modeloLista.addElement("Discapacitado: Si");
        } else {
            modeloLista.addElement("Discapacitado: No");
        }

        ListDatosCliente.setModel(modeloLista);
        jScrollPane2.setViewportView(ListDatosCliente);
    }

    public String formatoFecha(Calendar calendar) {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = formatoFecha.format(calendar.getTime());
        return fechaFormateada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListDatosCliente;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cbxVigencia;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panCosto;
    private javax.swing.JPanel panEntrar;
    private javax.swing.JPanel panFondoBlanco;
    private javax.swing.JPanel panHeader;
    private javax.swing.JTextField txfRfc;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtMonto;
    private javax.swing.JLabel txtRfc;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtVigencia;
    // End of variables declaration//GEN-END:variables
}
